---
- hosts: dev
  become: true
  vars:
    jenkins_version: 2.8
    directories:
      - file: slave.conf
        path: /home/jenkins/jenkins-slave/config
      - file: slave-service.sh
        path: /etc/init.d/jenkins-slave
  tasks:
    # - name: update
    #   apt: update_cache=true
    # # - name: repo
    # #   apt_repository: repo='ppa:openjdk-r/ppa'
    # - name: install
    #   apt: name=openjdk-8-jdk update_cache=true
    # # - name: set jdk
    # #   command: /usr/sbin/alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
    # - name: user jenkins
    #   user: name=jenkins create_home=true home=/home/jenkins shell=/bin/bash password={{"jenkins" | password_hash('sha512')}}
    # - name: slave home
    #   command: mkdir /home/jenkins/jenkins-slave
    #   ignore_errors: true
    - name: get file
      get_url: >
           url=https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/{{jenkins_version}}/remoting-{{jenkins_version}}.jar
           dest=/home/jenkins/jenkins-slave/slave.jar
      register: url_out
    - debug : var=url_out
    # - name: copy
    #   copy: src=files/{{item.file}} dest=/{{item.path}}
    #   with_items:
    #     - "{{directories}}"
    # - name: change
    #   shell: |
    #       chown -R jenkins:jenkins /home/jenkins
    #       chmod +x /etc/init.d/jenkins-slave && systemctl enable  jenkins-slave
